apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: access-test
  name: access-test
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: access-test
  strategy: {}
  template:
    metadata:
      labels:
        app: access-test
    spec:
      containers:
      - image: pauseandlearn/static-web:v1.0.0
        name: static-web
        ports:
        - containerPort: 80
          name: http
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: access-test-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: access-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

